### ISSUE TITLE
Rails Engine - (erb):14:in `<main>': uninitialized constant Chamber (NameError)

### ISSUE THREAD

**Issue by Chrisgo-75** [thekompanee/chamber#47]
I'm building a Rails Engine to hold database tables (models) that various Rails application need to use. I have included the Chamber gem in my various Rails 4 applications and like it!

Including it with this Rails engine and running rspec tests produces the below:

    (erb):14:in `<main>': uninitialized constant Chamber (NameError)

I am able to successfully install the Chamber gem and encrypt my settings. Not sure where to begin to debug the "uninitialized constant error".

Thanks
Chris

**Comment by Chrisgo-75** [comment]
If it helps any, will paste below the full output.

```
ruby-2.3.1-rg266@railsengine_cals_db ~/ror_dev/tests/engines/cals_db (develop) $ rspec spec/
(erb):14:in `<main>': uninitialized constant Chamber (NameError)
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:391:in `secrets'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:178:in `key_generator'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:206:in `message_verifier'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/globalid-0.3.7/lib/global_id/railtie.rb:25:in `block (2 levels) in <class:Railtie>'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /home/cgarndt/ror_dev/tests/engines/cals_db/spec/dummy/config/environment.rb:5:in `<top (required)>'
	from /home/cgarndt/ror_dev/tests/engines/cals_db/spec/rails_helper.rb:7:in `require'
	from /home/cgarndt/ror_dev/tests/engines/cals_db/spec/rails_helper.rb:7:in `<top (required)>'
	from /home/cgarndt/ror_dev/tests/engines/cals_db/spec/models/cals_db/ex_test_spec.rb:1:in `require'
	from /home/cgarndt/ror_dev/tests/engines/cals_db/spec/models/cals_db/ex_test_spec.rb:1:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/bin/rspec:22:in `load'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/bin/rspec:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jfelchner** [comment]
@Chrisgo-75 remember that when it comes to engines, your app is actually in `spec/dummy` and your engine is basically a gem, so if you want to use Chamber in your engine, you need to `require 'chamber'` just like any other gem.  Bundler won't do it for you.

If that doesn't solve it for you, I can reopen.

**Comment by Chrisgo-75** [comment]
Get a different error when trying to run Rails Console...

@jfelchner Thank you ... in adding `require 'chamber'` in engine.rb resolved the error.

When I cd to `spec/dummy/` and try to open rails console via `$ rails console` I get the following error `Failed to decrypt _secure_db_username (with an encrypted value of...`.  I did re-encrypt my values and I still get the error.

Will paste below the full error message:

```
ruby-2.3.1-rg266@railsengine_cals_db ~/ror_dev/tests/engines/cals_db/spec/dummy (uninitialized_constant_chamber) $ rails c
/usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/filters/failed_decryption_filter.rb:32:in `block in execute': Failed to decrypt _secure_db_username (with an encrypted value of 'Ned2TU8u+4dE1SLd+tCn7JK5vHn4jaUj41I+Kuw5pjSifNVgzSTSUMN6kwup+KG+lClBiR0LCNJMpAdHKE35+XoFzqKBT/oFHlKiKQGt6YplE4yhCa6buwwXj66LHgLjJOVQF3pkDeCG/5/f009wjaOwHGKdO73CCw9oJHaKFYzBmPNHoa1MwnoFK7WtkbFmq3RxA9mXk3ZzlrVZOP9cMC1+0HmidOVXGU1MJUg6jSivRMXJpVfwGTLbfFZwO/BK3k+tFCk9bCjSF1ae2S9iXruZfzTuMlOQ5ITMikAof3BJPJcSLaSmdvKiMYBMqcQCwpPBE/Ud+SuqgMV0QYV9EQ==') in your settings. (Chamber::Errors::DecryptionFailure)
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/filters/failed_decryption_filter.rb:25:in `each_pair'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/filters/failed_decryption_filter.rb:25:in `execute'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/filters/failed_decryption_filter.rb:15:in `execute'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/settings.rb:263:in `block in data'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/settings.rb:262:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/settings.rb:262:in `inject'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/settings.rb:262:in `data'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/settings.rb:285:in `respond_to_missing?'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/instance.rb:38:in `respond_to?'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber/instance.rb:38:in `respond_to_missing?'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber.rb:30:in `respond_to?'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/chamber-2.9.1/lib/chamber.rb:30:in `method_missing'
	from (erb):14:in `<main>'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:391:in `secrets'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:178:in `key_generator'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:206:in `message_verifier'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/globalid-0.3.7/lib/global_id/railtie.rb:25:in `block (2 levels) in <class:Railtie>'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/local/rvm/rubies/ruby-2.3.1-rg266/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /home/cgarndt/ror_dev/tests/engines/cals_db/spec/dummy/config/environment.rb:5:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.3.1-rg266@railsengine_cals_db/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:13:in `require'
	from bin/rails:13:in `<main>'
```

**Comment by Chrisgo-75** [comment]
@jfelchner - Any ideas on what might be the issue on this error "Failed to decrypt _secure_db_username (with an encrypted value of..."?  (above has the full error report).

**Comment by Chrisgo-75** [comment]
@jfelchner - problem fixed. Added private key file to dummy app directory ... makes sense.
